# +------------------+
# |                  |
# | Plugin coded by  |
# |     Keynadi      |
# |                  |
# +------------------+
#
# ! Every duration have to be in minecraft ticks !
#
#Delay before sending vote message
#20 ticks = 1 second
delay: 400

delimiter: " | "

playersdatasavetype: 2 #Plugin has two types of if player answered data saving. 1: All data saved in one config file. With big number of players may cause troubles. 2: Each players gets his own file where list of questions is contained. May cause troubles with /bq update

layout: "==================\n%question%\n\n%answers%\n==================" #adding more than 1 "%answers%" will cause troubles

messages:
  successfulvote: "&aYou successfully voted!"
  alreadyvoted: "&cYou already voted on this question!"
  nowbroadcasting: "&aQuestions are now broadcasting."
  nolongerbroadcasting: "&aQuestions no longer broadcasting."
  alreadybroadcasting: "&cNothing happened. Questions already broadcasting."
  alreadystoppedbroadcasting: "&cNothing happened. Questions weren't broadcasting."
  reload: "&aConfig has been reloaded!"
  hoveranswertext: "&fSend &b%answer% &fas an answer." #Answer in chat hover
  questionnotfound: "&cThere is no question with this number"
  updatesuccessful: "&aUpdate successful"

  nopermissions: "&cYou don't have permissions to do that"

  help: "&fBetter&bQuestions &fHelp\n&f/bq create - &bcreate new question\n&f/bq on|off - &bturn on/off plugin notifies for player\n&f/bq rl - &breload configuration file\n&f/bq view - &bview question statistic"

  title:
    sendquestionchat: "&aSend your question in chat"
    sendasnwerschat: "&aSend your answers in chat"
    answerssecondline: "Example: Yes, No, Maybe"
    questioncreated: "&aQuestion has been created!"
    questioncreatedsecondline: "/bq on - to turn on broadcasting."

  usage:
    view: "/bq view [questionNumber]"
    update: "/bq update [questionNumber]" #Remove all answers correspond to that question


#Is questions broadcasting?
active: true